language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - sudo composer self-update
  - composer install

script:
  - vendor/bin/atoum -d specs
  - echo
  - echo
  - php tests/functionnal.php
